stages:
    - configure
    - build

configure:
    stage: configure
    image: debian:latest
    before_script:
      - apt-get update
      - apt-get install -y gettext-base
    script:
        - ./configure.sh
    artifacts:
        paths:
            - Dockerfile

docker-build-master:
  # Official docker image.
  image: docker:18.09.7
  stage: build
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:18.09.7-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"

